default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: tuber_api_dev
  username: development
  password: development

test:
  <<: *default
  database: tuber_api_test
  username: development
  password: development

production:
  <<: *default
  database: tuber_api_prod
  username: development
  password: development

