default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: tuber_api_dev
  username: scott
  password: scott

test:
  <<: *default
  database: tuber_api_test
  username: scott
  password: scott

production:
  <<: *default
  database: tuber_api_prod
  username: scott
  password: scott

